apiVersion: v1
kind: Namespace
metadata:
  name: nginx-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app1
  template:
    metadata:
      labels:
        app: nginx-app1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app1-service
  namespace: nginx-app1
spec:
  type: ClusterIP
  selector:
    app: nginx-app1
  ports:
  - port: 80
    targetPort: 80
