
# Node configuration
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: <admin_ip>
  bindPort: 6443
nodeRegistration:
# name: <NodeName> # hostname by default
  taints: []
  kubeletExtraArgs:
    - name: node-ip
      value: <admin_ip>
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
rotateCertificates: true
