apiVersion: v1
kind: Namespace
metadata:
  name: simple-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-app-pvc
  namespace: simple-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: local-path
