#!/usr/bin/bash


declare -r rsc_dir='/home/admin/rsc'
declare -r output_dir='/tmp/gen'
rm -rf "${rsc_dir}"
rm -rf "${output_dir}"

# Perform some cleanup
apt-get clean
# Remove package list (will be regenerated by apt update)
rm -rf /var/lib/apt/lists/*
journalctl --vacuum-size=1G &>/dev/null
