apiVersion: v1
kind: Service
metadata:
  name: test-service
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.11.100
    kube-vip.io/vipHost: admin.lab.ln
  labels:
    implementation: kube-vip
spec:
  type: LoadBalancer
  loadBalancerClass: "kube-vip-admin-lb"
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-nginx
